import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Navbar2 from "@/components/Navbar2";
import { cookies } from 'next/headers';//only for making GET req manually 
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function verify() {
  try {
    const cookieStore = await cookies();
    const token = cookieStore.get("token")?.value;
    if (!token) return false;

    const res = await fetch(`${process.env.NEXT_PUBLIC_Server_url}/api/users/profile`, {
      headers: {
        Cookie: `token=${token}`, // Pass cookie manually 
      },
      cache: "no-store", // avoid caching
    });

    return res.ok;
  } catch (err) {
    console.error("Auth error:", err);
    return false;
  }
}


export default async function RootLayout({ children }) {
  const check = await verify();
  return (
    <html lang="en">

      <body >
        {check ? <Navbar2 /> : <Navbar />}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
